refresh materialized view section;
refresh materialized view section_paragraph;
refresh materialized view section_paragraph_xref;
refresh materialized view section_paragraph_fig;
refresh materialized view section_paragraph_table;
refresh materialized view sub1section;
refresh materialized view sub1section_paragraph;
refresh materialized view sub1section_paragraph_xref;
refresh materialized view sub1section_paragraph_fig;
refresh materialized view sub1section_paragraph_table;
refresh materialized view sub2section;
refresh materialized view sub2section_paragraph;
refresh materialized view sub2section_paragraph_xref;
refresh materialized view sub2section_paragraph_fig;
refresh materialized view sub2section_paragraph_table;
refresh materialized view sub3section;
refresh materialized view sub3section_paragraph;
refresh materialized view sub3section_paragraph_xref;
refresh materialized view sub3section_paragraph_fig;
refresh materialized view sub3section_paragraph_table;
refresh materialized view sub4section;
refresh materialized view sub4section_paragraph;
refresh materialized view sub4section_paragraph_xref;
refresh materialized view sub4section_paragraph_fig;
refresh materialized view sub4section_paragraph_table;
refresh materialized view sub5section;

insert into paragraph select * from sec_para_final where pmcid not in (select pmcid from paragraph);
