\i covid_sentence_refresh_n3c.sql
\i covid_sentence_refresh_ncats.sql
\i covid_sentence_refresh_pubchem_compounds.sql
\i covid_sentence_refresh_pubchem_genes.sql
\i covid_sentence_refresh_pubchem_proteins.sql
\i covid_sentence_refresh_pubchem_substances.sql
